baseURL: "https://iaziz786.com/"
languageCode: en-us
title: Mohammad Aziz
theme: terminal
favicon: "images/favicon.svg"

params:
  socialIcons:
    - name: "x.com"
      url: "https://x.com/iAziz786"
    - name: "github"
      url: "https://github.com/iAziz786"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/iAziz786"

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai

menu:
  main:
    - identifiers: home
      name: home
      url: /
      weight: 1
    - identifiers: blog
      name: blog
      url: /blog/
      weight: 2
    - identifiers: projects
      name: projects
      url: /projects/
      weight: 3
    - identifiers: about
      name: about
      url: /about/
      weight: 4
